# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsciinemaTrim < Formula
  desc "Trim asciinema's record file"
  homepage "https://github.com/suzuki-shunsuke/asciinema-trim"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/asciinema-trim/releases/download/v0.1.0/asciinema-trim_darwin_arm64.tar.gz"
      sha256 "77880f05938c94443a6437dba311fe08b8cc3eebfe686ac63c401b71ec37bb50"

      def install
        bin.install "asciinema-trim"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/asciinema-trim/releases/download/v0.1.0/asciinema-trim_darwin_amd64.tar.gz"
      sha256 "bb519f6bef3236491ee294866fae1f9fb2da5fa72497045375d67c82077e573b"

      def install
        bin.install "asciinema-trim"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/suzuki-shunsuke/asciinema-trim/releases/download/v0.1.0/asciinema-trim_linux_arm.tar.gz"
      sha256 "fa2207970091ab5a2cf6d1f2b2dd8d106f74d82d7fd4c715451b0ea22cce279a"

      def install
        bin.install "asciinema-trim"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/asciinema-trim/releases/download/v0.1.0/asciinema-trim_linux_amd64.tar.gz"
      sha256 "94f330b32cb3bcd8e1b1a49768dd7b534b929efb7cdbca1b39d5a4502b3c18f1"

      def install
        bin.install "asciinema-trim"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suzuki-shunsuke/asciinema-trim/releases/download/v0.1.0/asciinema-trim_linux_arm64.tar.gz"
      sha256 "27cfd9312f75788947e67c5b959f07384d04b61b3a646b6040040f6a85c4c57d"

      def install
        bin.install "asciinema-trim"
      end
    end
  end

  test do
    system "#{bin}/asciinema-trim --version"
  end
end
