# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AsciinemaTrim < Formula
  desc "Trim asciinema's record file"
  homepage "https://github.com/suzuki-shunsuke/asciinema-trim"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/suzuki-shunsuke/asciinema-trim/releases/download/v0.1.2/asciinema-trim_darwin_arm64.tar.gz"
      sha256 "2128587018a60bf32c324f31657d87dd700db129bfca2892153292e03a87675a"

      def install
        bin.install "asciinema-trim"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/asciinema-trim/releases/download/v0.1.2/asciinema-trim_darwin_amd64.tar.gz"
      sha256 "684cd48ac125f2d932cb1ec7b76c84a2c33b1aa7a6474c13a1c91a711d2e0ec7"

      def install
        bin.install "asciinema-trim"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/suzuki-shunsuke/asciinema-trim/releases/download/v0.1.2/asciinema-trim_linux_amd64.tar.gz"
      sha256 "dd3889051e0d0833c0959ac21761938fbf889a994d78a29fc2a942c3ee6d766c"

      def install
        bin.install "asciinema-trim"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/suzuki-shunsuke/asciinema-trim/releases/download/v0.1.2/asciinema-trim_linux_arm64.tar.gz"
      sha256 "5bf790368b3bccd98ad5a3f48b8eb43379e839d782cd6453f88496c2259a1c97"

      def install
        bin.install "asciinema-trim"
      end
    end
  end

  test do
    system "#{bin}/asciinema-trim --version"
  end
end
