# This file was generated by GoReleaser. DO NOT EDIT.
cask "asciinema-trim" do
  desc "Trim asciinema's record file"
  homepage "https://github.com/suzuki-shunsuke/asciinema-trim"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "asciinema-trim"

  on_macos do
    on_intel do
      url "https://github.com/suzuki-shunsuke/asciinema-trim/releases/download/v0.1.4/asciinema-trim_darwin_amd64.tar.gz"
      sha256 "fc56d45b38fcb8fd7f6b9a19428e507be4078c011816885046bba2035271f1d3"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/asciinema-trim/releases/download/v0.1.4/asciinema-trim_darwin_arm64.tar.gz"
      sha256 "c0ca4b8205028f75dceab80f2c65c55f7828db98b101f84107de4250d265592a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/suzuki-shunsuke/asciinema-trim/releases/download/v0.1.4/asciinema-trim_linux_amd64.tar.gz"
      sha256 "72e4b003fef3bc3ab00c1a346494d11d0fb93b1bda649fb9e60bdb13d8c3da4d"
    end
    on_arm do
      url "https://github.com/suzuki-shunsuke/asciinema-trim/releases/download/v0.1.4/asciinema-trim_linux_arm64.tar.gz"
      sha256 "ba5d261865e88810df931534715805446aa0a467b64e96adbff98475b49f86f5"
    end
  end

  # No zap stanza required
end
